version: '3.5'
volumes:
  db_data:
  app_data:
services:
  db:
    build:
      context: ../../
      dockerfile: run/docker/postgres/Dockerfile
    image: insdb/insdb_db
    volumes:
      - db_data:/srv/postgresql/data/
    expose:
      - '5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  app:
    build:
      context: ../../
      dockerfile: run/docker/app/Dockerfile
    image: insdb/insdb_app
    command: |
      /wait_for_it.sh db:5432 -t 0 -- gunicorn
      --workers 8
      --timeout 120
      --worker-class aiohttp.worker.GunicornWebWorker
      --log-level debug
      --error-logfile=-
      --preload
      -b 0.0.0.0:8000 voseq.wsgi
    volumes:
      - app_data:/data
      - /logs
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'voseq.settings.production'
  nginx:
    build:
      context: ../../
      dockerfile: run/docker/nginx/Dockerfile
    image: insdb/insdb_nginx
    volumes:
      - app_data:/data
    ports:
      - "8082:80"
      - "4432:443"
    depends_on:
      - app
  celery_worker:
    image: insdb/insdb_app
    command: /wait_for_it.sh redis:6379
      --timeout=0 --
      /wait_for_it.sh db:5432
      --timeout=0 --
      celery
      --app=voseq
      worker
      --hostname=default@%h
      --loglevel=info
      --concurrency=2
      --queues=default
    depends_on:
      - redis
      - db
    environment:
      C_FORCE_ROOT: 'True'
      DJANGO_SETTINGS_MODULE: 'voseq.settings.production'
    volumes:
      - app_data:/data
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - app_data:/data
    expose:
      - '6379'
